= jOOQ Codegen Plugin

== Overview

image:https://circleci.com/gh/bombinating/jooq-gradle-plugin/tree/master.svg?style=svg["CircleCI", link="https://circleci.com/gh/bombinating/jooq-gradle-plugin/tree/master"] image:https://sonarcloud.io/api/project_badges/measure?project=bombinating_jooq-gradle-plugin&metric=alert_status["SonarCloud", link="https://sonarcloud.io/dashboard?id=bombinating_jooq-gradle-plugin"]

A https://gradle.org[Gradle] plugin for working with the https://www.jooq.org[jOOQ] https://www.jooq.org/doc/3.11/manual/code-generation/codegen-configuration/[code generation tool] that supports the https://docs.gradle.org/current/userguide/kotlin_dsl.html[Gradle Kotlin DSL].

This started as a Kotlin port of the Groovy-based https://github.com/etiennestuder/gradle-jooq-plugin[gradle-jooq-plugin] and was initially developed because it was decided that the Groovy plugin https://github.com/etiennestuder/gradle-jooq-plugin/pull/91[would not add Kotlin DSL support].

== Using the plugin

The plugin id needs to be added to the `plugins` block in the `build.gradle.kts` file in order to be used.

[source,build.gradle.kts]
----
plugins {
    id("dev.bombinating.jooq-codegen") version "3.12.1"
}
----

== Setting the code generation classpath

The JDBC driver for introspecting the database must be provided in the `dependencies` block using the `jooqRuntime` scope, which is created by the plugin.

[source,build.gradle.kts]
----
dependencies {
    jooqRuntime(group = "org.postgresql", name = "postgresql", version = "42.2.6")
}
----

== Using the extension

The plugin defines an extension, `jooq`, which (optionally) allows both the version and edition of the jOOQ code generation library to be defined, as well as information about the code generation itself.

If the `edition` or `version` is not specified, they default to `OpenSource` and the same version as the plugin (e.g., `3.12.1`), respectively.

The code generation properties (`logging`, `jdbc` and `generator`) come from the jOOQ code generation `Configuration` class (from the https://www.jooq.org/xsd/jooq-runtime-3.12.0.xsd[jOOQ codegen XSD]). The plugin provides extension methods to define the properties in a "closure" style.

|===
|Property | Description | Example

|`edition`|https://www.jooq.org/download/versions[jOOQ edition to use] (OpenSource, Pro, ProJava8, ProJava6)|`JooqEdition.Pro`
|`version`|jOOQ version to use|`3.12.1`
|`logging`|jOOQ code generation config logging setting|`Logging.TRACE`
|`jdbc`|jOOQ code generation config jdbc settings`
l|
jooq {
    url = ...
    user = ...
    password = ...
    ...
}
|`generator`|jOOQ code generation config generator settings`
l|generator {
    database {
        ...
    }
    target {
        ...
    }
    ...
}
|===

== Default task

The plugin also defines a task, `jooq`, which invokes the jOOQ code generation functionality using the configuration in the `jooq` extension block.

[source,bash]
----
$ ./gradlew jooq
----

There are no dependencies on this task and this task does not have any dependencies on other tasks. Therefore, after running the `jooq` task, it is necessary to run the `build` task. It is also necessary to add the directory into which the code is being generated into the source set.

Here's an example build.gradle.kts file. The database URL, schema, username and password are passed in via the command-line or in an external gradle.properties file.

[source,bash]
----
$ ./gradlew jooq build -PdbUrl=... -PdbUsername=... -PdbPassword=... -PdbSchema=...
----

[source,build.gradle.kts]
----
import dev.bombinating.gradle.jooq.*
...
val dbUrl: String? by project
val dbUsername: String? by project
val dbPassword: String? by project
val dbSchema: String? by project
val genDir: String = "$projectDir/generated/src/main/java"
...
sourceSets["main"].java {
    srcDir(genDir)
}
...
jooq {
    edition = JooqEdition.Professional
    jdbc {
        driver = "oracle.jdbc.driver.OracleDriver"
        url = dbUrl
        user = dbUsername
        password = dbPassword
    }
    generator {
        database {
            name = "org.jooq.meta.oracle.OracleDatabase"
            includes = ".*"
            excludes = "^BIN\\$.*|flyway_schema_history"
            inputSchema = dbSchema
        }
        target {
            directory = genDir
            packageName = "com.acme.domain.generated"
        }
    }
    logging = Logging.INFO
}
----

== Creating tasks

To define additional jOOQ code generation configurations, register/create tasks of type `JooqTask`.

The `JooqTask` has the same three code generation properties as the jOOQ extension. The jOOQ `edition` and `version` properties are not available in the task.

|===
|Property | Description | Example

|`logging`|jOOQ code generation config logging setting|`Logging.TRACE`
|`jdbc`|jOOQ code generation config jdbc settings`
l|
jooq {
    url = ...
    user = ...
    password = ...
    ...
}
|`generator`|jOOQ code generation config generator settings`
l|generator {
    database {
        ...
    }
    target {
        ...
    }
    ...
}
|===

For example:

[source,build.gradle.kts]
----
import dev.bombinating.gradle.jooq.*
...
tasks.register<JooqTask>("jooqAccounting") {
    jdbc {
        ...
    }
    generator {
        ...
    }
    logging = ...
}
----

This task can be invoked like any other Gradle task:

[source,bash]
----
$ ./gradlew jooqAccounting
----

== License

http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0.]
