name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '1.8', '11', '13' ]
    name: Java ${{ matrix.java }} Build
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Gradle
      env:
        JOOQ_CONTAINER_TESTS: true
        JOOQ_PRO_TESTS: true
        JOOQ_REPO_URL: ${{ secrets.JOOQ_REPO_URL }}
        JOOQ_REPO_USERNAME: ${{ secrets.JOOQ_REPO_USERNAME }}
        JOOQ_REPO_PASSWORD: ${{ secrets.JOOQ_REPO_PASSWORD }}
      run: sh ./gradlew build
    - name: Upload Artifacts
      uses: actions/upload-artifact@master
      with:
        name: libs-java-${{ matrix.java }}
        path: build/libs
    - name: Upload Test Results
      uses: actions/upload-artifact@master
      with:
        name: tests-java-${{ matrix.java }}
        path: build/reports/tests/test
    - name: Upload Static Analysis
      uses: actions/upload-artifact@master
      with:
        name: analysis-java-${{ matrix.java }}
        path: build/reports/detekt
