name: Master Branch Build

on:
  push:
    branches:
      - master

jobs:
  master-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '1.8', '11', '13' ]
    name: Build Master Branch Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Gradle
      env:
        GRADLE_SCAN_PUBLISH: ${{ matrix.java == '1.8' }}
        JOOQ_CONTAINER_TESTS: true
        JOOQ_PRO_TESTS: true
        JOOQ_REPO_URL: ${{ secrets.JOOQ_REPO_URL }}
        JOOQ_REPO_USERNAME: ${{ secrets.JOOQ_REPO_USERNAME }}
        JOOQ_REPO_PASSWORD: ${{ secrets.JOOQ_REPO_PASSWORD }}
      run: sh ./gradlew build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: libs-java-${{ matrix.java }}
        path: build/libs
    - name: Upload Test Results
      uses: actions/upload-artifact@v1
      with:
        name: tests-java-${{ matrix.java }}
        path: build/reports/tests/test
    - name: Upload Static Analysis
      uses: actions/upload-artifact@v1
      with:
        name: analysis-java-${{ matrix.java }}
        path: build/reports/detekt
  artifactory-publish:
    needs: master-build
    runs-on: ubuntu-latest
    name: Publish Master Branch Java ${{ matrix.java }} to Artifactory
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download Java 8 libs
        uses: actions/download-artifact@v1
        with:
          name: libs-java-1.8
          path: build/libs
      - name: Publish to Artifactory
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: sh ./gradlew artifactoryPublish -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY
        if: !contains(github.event.head_commit.message, 'pre tag commit')