name: Tag Build

on:
  push:
    tags:
      - *

jobs:
  tag-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '1.8', '11', '13' ]
    name: Build Tag Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Gradle
      env:
        JOOQ_CONTAINER_TESTS: true
        JOOQ_PRO_TESTS: true
        JOOQ_REPO_URL: ${{ secrets.JOOQ_REPO_URL }}
        JOOQ_REPO_USERNAME: ${{ secrets.JOOQ_REPO_USERNAME }}
        JOOQ_REPO_PASSWORD: ${{ secrets.JOOQ_REPO_PASSWORD }}
      run: sh ./gradlew build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: libs-java-${{ matrix.java }}
        path: build/libs
    - name: Upload Test Results
      uses: actions/upload-artifact@v1
      with:
        name: tests-java-${{ matrix.java }}
        path: build/reports/tests/test
    - name: Upload Static Analysis
      uses: actions/upload-artifact@v1
      with:
        name: analysis-java-${{ matrix.java }}
        path: build/reports/detekt
  bintray-publish:
    needs: tag-build
    runs-on: ubuntu-latest
    name: Publish Tag Java ${{ matrix.java }} to Bintray
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download Java 8 libs
        uses: actions/download-artifact@v1
        with:
          name: libs-java-1.8
          path: build/libs
      - name: Deploy to Bintray
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: sh ./gradlew bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY
  gradle-publish:
    needs: tag-build
    runs-on: ubuntu-latest
    name: Publish Tag Java ${{ matrix.java }} to Gradle Plugin Portal
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download Java 8 libs
        uses: actions/download-artifact@v1
        with:
          name: libs-java-1.8
          path: build/libs
      - name: Publish to Gradle Plugin Portal
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: sh ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET